using System.Reflection;
using System.Text;
using System.Xml;

// Generates per-test [ConditionalFact(Skip = ...)]/[ConditionalTheory(Skip = ...)] override
// members for every test that failed in a trx run, as .Skips.cs partial-class files next to the
// derivation sources. Usage:
//
//   GenerateSkips <run.trx> <FunctionalTests.dll> <FunctionalTests source root>
//
// The derivation classes must be declared partial; the tool prints any class that is not.

if (args.Length != 3)
{
    Console.Error.WriteLine("usage: GenerateSkips <run.trx> <test assembly> <source root>");
    return 1;
}

var trxPath = Path.GetFullPath(args[0]);
var assemblyPath = Path.GetFullPath(args[1]);
var sourceRoot = Path.GetFullPath(args[2]);
const string reason = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.";

// resolve dependencies from the test assembly's own bin folder
var binDir = Path.GetDirectoryName(assemblyPath)!;
AppDomain.CurrentDomain.AssemblyResolve += (_, e) =>
{
    var name = new AssemblyName(e.Name).Name!;
    var candidate = Path.Combine(binDir, name + ".dll");
    return File.Exists(candidate) ? Assembly.LoadFrom(candidate) : null;
};

var assembly = Assembly.LoadFrom(assemblyPath);

// gather failing (class, method) pairs, and every (class, method) that appeared at all, so a
// theory whose cases all failed can be told apart from one with passing cases
var failed = new HashSet<(string Class, string Method)>();
var seen = new Dictionary<(string Class, string Method), (int Total, int Failed)>();

using (var xml = XmlReader.Create(trxPath))
{
    while (xml.Read())
    {
        if (xml.NodeType != XmlNodeType.Element || xml.Name != "UnitTestResult")
            continue;

        var testName = xml.GetAttribute("testName");
        var outcome = xml.GetAttribute("outcome");
        if (testName is null || outcome is null)
            continue;

        // strip theory arguments: Ns.Class.Method(arg: x, ...)
        var paren = testName.IndexOf('(');
        var fqn = paren < 0 ? testName : testName[..paren];
        var lastDot = fqn.LastIndexOf('.');
        if (lastDot < 0)
            continue;

        var key = (fqn[..lastDot], fqn[(lastDot + 1)..]);
        var counts = seen.TryGetValue(key, out var c) ? c : (0, 0);
        counts.Item1++;
        if (outcome == "Failed")
        {
            counts.Item2++;
            failed.Add(key);
        }

        seen[key] = counts;
    }
}

Console.WriteLine($"failing methods: {failed.Count}");

var mixedTheories = failed.Where(k => seen[k].Failed < seen[k].Total).ToList();
Console.WriteLine($"of which theories with passing cases (skipped whole): {mixedTheories.Count}");

var byClass = failed.GroupBy(k => k.Class).OrderBy(g => g.Key);
var emitted = 0;
var missing = new List<string>();
var notPartial = new List<string>();

foreach (var group in byClass)
{
    var type = assembly.GetType(group.Key);
    if (type is null || type.IsAbstract)
    {
        missing.Add(group.Key + (type is null ? " (type not found)" : " (abstract)"));
        continue;
    }

    // the declaration chain: a nested test class needs partial wrappers for each declaring type
    var chain = new List<Type>();
    for (var t = type; t is not null; t = t.DeclaringType)
        chain.Insert(0, t);

    var sb = new StringBuilder();
    var ns = type.Namespace!;
    sb.AppendLine("// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.");
    sb.AppendLine("// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data");
    sb.AppendLine("#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery");
    sb.AppendLine();
    sb.AppendLine($"namespace {ns};");
    foreach (var t in chain)
    {
        sb.AppendLine();
        sb.AppendLine($"partial class {t.Name}");
        sb.AppendLine("{");
    }

    var any = false;
    foreach (var (_, methodName) in group.OrderBy(k => k.Method))
    {
        var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => m.Name == methodName && (m.IsVirtual && !m.IsFinal || m.DeclaringType != type))
            .DistinctBy(m => string.Join(",", m.GetParameters().Select(p => p.ParameterType.FullName)))
            .ToList();

        if (methods.Count == 0)
        {
            missing.Add($"{group.Key}.{methodName} (no overridable method)");
            continue;
        }

        // a method already overridden in the derivation source would collide with a generated
        // member of the same partial class; leave those for manual attention
        if (methods.Any(m => m.DeclaringType == type))
        {
            missing.Add($"{group.Key}.{methodName} (already overridden in the derivation)");
            continue;
        }

        foreach (var method in methods)
        {
            if (method.IsGenericMethodDefinition)
            {
                missing.Add($"{group.Key}.{methodName} (generic method)");
                continue;
            }

            var factAttribute = method.GetBaseDefinition().GetCustomAttributesData()
                .Concat(method.GetCustomAttributesData())
                .FirstOrDefault(a => a.AttributeType.Name is "ConditionalFactAttribute" or "ConditionalTheoryAttribute" or "FactAttribute" or "TheoryAttribute");
            var attributeName = factAttribute?.AttributeType.FullName
                ?? (method.GetParameters().Length > 0 ? "Xunit.ConditionalTheoryAttribute" : "Xunit.ConditionalFactAttribute");

            var parameters = method.GetParameters();
            var paramList = string.Join(", ", parameters.Select(p => $"{CSharpName(p.ParameterType)} {p.Name}"));
            var argList = string.Join(", ", parameters.Select(p => p.Name));
            var returnType = CSharpName(method.ReturnType);
            var body = method.ReturnType == typeof(void)
                ? $"base.{methodName}({argList});"
                : $"return base.{methodName}({argList});";

            // a non-virtual test cannot be overridden; shadowing hides the base slot from xunit
            // discovery, so the skip attribute on the shadow is the one that takes effect
            var modifier = method.IsVirtual && !method.IsFinal ? "override" : "new";

            sb.AppendLine();
            sb.AppendLine($"    [{attributeName[..^9]}(Skip = \"{reason}\")]");
            sb.AppendLine($"    public {modifier} {returnType} {methodName}({paramList})");
            sb.AppendLine("    {");
            sb.AppendLine($"        {body}");
            sb.AppendLine("    }");
            any = true;
            emitted++;
        }
    }

    foreach (var _ in chain)
    {
        sb.AppendLine();
        sb.AppendLine("}");
    }

    if (!any)
        continue;

    // find the source file declaring the class, to place the .Skips.cs next to it and mark the
    // whole declaration chain partial
    var sourceFile = Directory.EnumerateFiles(sourceRoot, "*.cs", SearchOption.AllDirectories)
        .Where(f => !f.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}") && !f.EndsWith(".Skips.cs"))
        .FirstOrDefault(f => File.ReadAllText(f).Contains($"class {type.Name} ") || File.ReadAllText(f).Contains($"class {type.Name}("));

    if (sourceFile is null)
    {
        missing.Add(group.Key + " (source file not found)");
        continue;
    }

    var source = File.ReadAllText(sourceFile);
    var edited = source;
    foreach (var t in chain)
        if (!edited.Contains($"partial class {t.Name}"))
            edited = new System.Text.RegularExpressions.Regex($@"(?<![\w.])class {System.Text.RegularExpressions.Regex.Escape(t.Name)}\b")
                .Replace(edited, $"partial class {t.Name}", 1);

    if (edited != source)
    {
        File.WriteAllText(sourceFile, edited);
        notPartial.Add(sourceFile);
    }

    File.WriteAllText(Path.Combine(Path.GetDirectoryName(sourceFile)!, type.Name + ".Skips.cs"), sb.ToString());
}

Console.WriteLine($"overrides emitted: {emitted}");
foreach (var m in missing.Distinct())
    Console.WriteLine($"UNRESOLVED: {m}");
foreach (var f in notPartial.Distinct())
    Console.WriteLine($"MARKED PARTIAL: {f}");

return 0;

static string CSharpName(Type type)
{
    if (type == typeof(void))
        return "void";
    if (type == typeof(bool))
        return "bool";
    if (type == typeof(int))
        return "int";
    if (type == typeof(string))
        return "string";
    if (type.IsArray)
        return CSharpName(type.GetElementType()!) + "[]";
    if (type.IsGenericType)
    {
        var name = type.GetGenericTypeDefinition().FullName!;
        name = name[..name.IndexOf('`')];
        var arguments = string.Join(", ", type.GetGenericArguments().Select(CSharpName));
        return $"global::{name}<{arguments}>";
    }

    if (type.IsNested)
        return $"global::{type.DeclaringType!.FullName!.Replace('+', '.')}.{type.Name}";

    return $"global::{type.FullName}";
}
