// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class BuiltInDataTypesCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_all_non_nullable_data_types()
    {
        return base.Can_insert_and_read_back_all_non_nullable_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_all_nullable_data_types_with_values_set_to_non_null()
    {
        return base.Can_insert_and_read_back_all_nullable_data_types_with_values_set_to_non_null();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_non_nullable_backed_data_types()
    {
        return base.Can_insert_and_read_back_non_nullable_backed_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_nullable_backed_data_types()
    {
        return base.Can_insert_and_read_back_nullable_backed_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_object_backed_data_types()
    {
        return base.Can_insert_and_read_back_object_backed_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_data_type()
    {
        return base.Can_query_using_any_data_type();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_data_type_nullable_shadow()
    {
        return base.Can_query_using_any_data_type_nullable_shadow();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_data_type_shadow()
    {
        return base.Can_query_using_any_data_type_shadow();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_nullable_data_type()
    {
        return base.Can_query_using_any_nullable_data_type();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_nullable_data_type_as_literal()
    {
        return base.Can_query_using_any_nullable_data_type_as_literal();
    }

}
