// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class CommandInterceptionCalciteTestBase
{

partial class CommandInterceptionCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_non_query_passively(bool async, bool inject)
    {
        return base.Intercept_non_query_passively(async, inject);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_non_query_to_replace_execution(bool async, bool inject)
    {
        return base.Intercept_non_query_to_replace_execution(async, inject);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task<string> Intercept_query_to_replace_result(bool async, bool inject)
    {
        return base.Intercept_query_to_replace_result(async, inject);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_query_to_suppress_command_creation(bool async, bool inject)
    {
        return base.Intercept_query_to_suppress_command_creation(async, inject);
    }

}

}
