// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class ComplexTypesTrackingCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_null_complex_property_with_default_values_and_multiple_properties(bool async)
    {
        return base.Can_null_complex_property_with_default_values_and_multiple_properties(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_save_default_values_in_optional_complex_property_with_multiple_properties(bool async)
    {
        return base.Can_save_default_values_in_optional_complex_property_with_multiple_properties(async);
    }

}
