// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class CustomConvertersCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_non_nullable_backed_data_types()
    {
        return base.Can_insert_and_read_back_non_nullable_backed_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_nullable_backed_data_types()
    {
        return base.Can_insert_and_read_back_nullable_backed_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_object_backed_data_types()
    {
        return base.Can_insert_and_read_back_object_backed_data_types();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_and_read_back_with_case_insensitive_string_key()
    {
        return base.Can_insert_and_read_back_with_case_insensitive_string_key();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_data_type_nullable_shadow()
    {
        return base.Can_query_using_any_data_type_nullable_shadow();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_using_any_nullable_data_type_as_literal()
    {
        return base.Can_query_using_any_nullable_data_type_as_literal();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Infer_type_mapping_from_in_subquery_to_item()
    {
        base.Infer_type_mapping_from_in_subquery_to_item();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_conditional_bool_with_value_conversion_is_used()
    {
        return base.Select_conditional_bool_with_value_conversion_is_used();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Value_conversion_is_appropriately_used_for_join_condition()
    {
        return base.Value_conversion_is_appropriately_used_for_join_condition();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Value_conversion_is_appropriately_used_for_left_join_condition()
    {
        return base.Value_conversion_is_appropriately_used_for_left_join_condition();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Value_conversion_on_enum_collection_contains()
    {
        base.Value_conversion_on_enum_collection_contains();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_bool_gets_converted_to_equality_when_value_conversion_is_used()
    {
        return base.Where_bool_gets_converted_to_equality_when_value_conversion_is_used();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_bool_gets_converted_to_equality_when_value_conversion_is_used_using_EFProperty()
    {
        return base.Where_bool_gets_converted_to_equality_when_value_conversion_is_used_using_EFProperty();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_bool_gets_converted_to_equality_when_value_conversion_is_used_using_indexer()
    {
        return base.Where_bool_gets_converted_to_equality_when_value_conversion_is_used_using_indexer();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_bool_with_value_conversion_inside_comparison_doesnt_get_converted_twice()
    {
        return base.Where_bool_with_value_conversion_inside_comparison_doesnt_get_converted_twice();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_conditional_bool_with_value_conversion_is_used()
    {
        return base.Where_conditional_bool_with_value_conversion_is_used();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_negated_bool_gets_converted_to_equality_when_value_conversion_is_used()
    {
        return base.Where_negated_bool_gets_converted_to_equality_when_value_conversion_is_used();
    }

}
