// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class FieldMappingCalciteTest
{

partial class EnforceFieldTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Include_collection_fields_only(bool tracking)
    {
        base.Include_collection_fields_only(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Include_collection_fields_only_for_navs_too(bool tracking)
    {
        base.Include_collection_fields_only_for_navs_too(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Include_collection_props_with_IReadOnlyCollection(bool tracking)
    {
        base.Include_collection_props_with_IReadOnlyCollection(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Include_collection_read_only_props(bool tracking)
    {
        base.Include_collection_read_only_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Include_reference_fields_only_only_for_navs_too(bool tracking)
    {
        base.Include_reference_fields_only_only_for_navs_too(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Include_reference_props_with_IReadOnlyCollection(bool tracking)
    {
        base.Include_reference_props_with_IReadOnlyCollection(tracking);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_collection_auto_props()
    {
        base.Load_collection_auto_props();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_collection_fields_only()
    {
        base.Load_collection_fields_only();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_collection_fields_only_only_for_navs_too()
    {
        base.Load_collection_fields_only_only_for_navs_too();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_collection_hiding_props()
    {
        base.Load_collection_hiding_props();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_collection_read_only_props()
    {
        base.Load_collection_read_only_props();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_reference_auto_props()
    {
        base.Load_reference_auto_props();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_reference_fields_only()
    {
        base.Load_reference_fields_only();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_reference_fields_only_only_for_navs_too()
    {
        base.Load_reference_fields_only_only_for_navs_too();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Load_reference_write_only_props_with_named_fields()
    {
        base.Load_reference_write_only_props_with_named_fields();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Projection_auto_props(bool tracking)
    {
        base.Projection_auto_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Projection_fields_only(bool tracking)
    {
        base.Projection_fields_only(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Projection_fields_only_only_for_navs_too(bool tracking)
    {
        base.Projection_fields_only_only_for_navs_too(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Projection_write_only_props_with_named_fields(bool tracking)
    {
        base.Projection_write_only_props_with_named_fields(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_constant_fields_only(bool tracking)
    {
        base.Query_with_conditional_constant_fields_only(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_constant_fields_only_only_for_navs_too(bool tracking)
    {
        base.Query_with_conditional_constant_fields_only_only_for_navs_too(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_constant_read_only_props(bool tracking)
    {
        base.Query_with_conditional_constant_read_only_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_constant_write_only_props_with_named_fields(bool tracking)
    {
        base.Query_with_conditional_constant_write_only_props_with_named_fields(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_param_auto_props(bool tracking)
    {
        base.Query_with_conditional_param_auto_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_param_fields_only_only_for_navs_too(bool tracking)
    {
        base.Query_with_conditional_param_fields_only_only_for_navs_too(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_param_read_only_props(bool tracking)
    {
        base.Query_with_conditional_param_read_only_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Query_with_conditional_param_write_only_props(bool tracking)
    {
        base.Query_with_conditional_param_write_only_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Simple_query_auto_props(bool tracking)
    {
        base.Simple_query_auto_props(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Simple_query_fields_only(bool tracking)
    {
        base.Simple_query_fields_only(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Simple_query_fields_only_for_navs_too(bool tracking)
    {
        base.Simple_query_fields_only_for_navs_too(tracking);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Simple_query_read_only_props(bool tracking)
    {
        base.Simple_query_read_only_props(tracking);
    }

}

}
