// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class ManyToManyTrackingCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_Attach_or_Update_a_many_to_many_with_mixed_set_and_unset_keys(bool useUpdate, bool async)
    {
        return base.Can_Attach_or_Update_a_many_to_many_with_mixed_set_and_unset_keys(useUpdate, async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_delete_with_many_to_many_composite_additional_pk_with_navs()
    {
        return base.Can_delete_with_many_to_many_composite_additional_pk_with_navs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_delete_with_many_to_many_composite_additional_pk_with_navs_unidirectional()
    {
        return base.Can_delete_with_many_to_many_composite_additional_pk_with_navs_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_delete_with_many_to_many_composite_with_navs()
    {
        return base.Can_delete_with_many_to_many_composite_with_navs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_delete_with_many_to_many_with_navs()
    {
        return base.Can_delete_with_many_to_many_with_navs();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_composite_additional_pk_with_navs(bool async)
    {
        return base.Can_insert_many_to_many_composite_additional_pk_with_navs(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_composite_additional_pk_with_navs_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_composite_additional_pk_with_navs_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_composite_with_navs_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_composite_with_navs_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_fully_by_convention_generated_keys(bool async)
    {
        return base.Can_insert_many_to_many_fully_by_convention_generated_keys(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_self_shared(bool async)
    {
        return base.Can_insert_many_to_many_self_shared(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_self_shared_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_self_shared_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_self_with_payload(bool async)
    {
        return base.Can_insert_many_to_many_self_with_payload(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_self_with_payload_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_self_with_payload_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_shared_with_payload(bool async)
    {
        return base.Can_insert_many_to_many_shared_with_payload(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_shared_with_payload_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_shared_with_payload_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_with_dangling_join_unidirectional(bool async, bool useTrackGraph, bool useDetectChanges)
    {
        return base.Can_insert_many_to_many_with_dangling_join_unidirectional(async, useTrackGraph, useDetectChanges);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_with_payload(bool async)
    {
        return base.Can_insert_many_to_many_with_payload(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_with_suspected_dangling_join(bool async, bool useTrackGraph, bool useDetectChanges)
    {
        return base.Can_insert_many_to_many_with_suspected_dangling_join(async, useTrackGraph, useDetectChanges);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_with_suspected_dangling_join_unidirectional(bool async, bool useTrackGraph, bool useDetectChanges)
    {
        return base.Can_insert_many_to_many_with_suspected_dangling_join_unidirectional(async, useTrackGraph, useDetectChanges);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Can_load_entities_in_any_order(int[] order)
    {
        base.Can_load_entities_in_any_order(order);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_replace_dependent_with_many_to_many(bool createNewCollection, bool async)
    {
        return base.Can_replace_dependent_with_many_to_many(createNewCollection, async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many()
    {
        return base.Can_update_many_to_many();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_composite_additional_pk_with_navs()
    {
        return base.Can_update_many_to_many_composite_additional_pk_with_navs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_composite_additional_pk_with_navs_unidirectional()
    {
        return base.Can_update_many_to_many_composite_additional_pk_with_navs_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_composite_shared_with_navs()
    {
        return base.Can_update_many_to_many_composite_shared_with_navs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_composite_with_navs()
    {
        return base.Can_update_many_to_many_composite_with_navs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_composite_with_navs_unidirectional()
    {
        return base.Can_update_many_to_many_composite_with_navs_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_self()
    {
        return base.Can_update_many_to_many_self();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_self_unidirectional()
    {
        return base.Can_update_many_to_many_self_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_self_with_payload()
    {
        return base.Can_update_many_to_many_self_with_payload();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_self_with_payload_unidirectional()
    {
        return base.Can_update_many_to_many_self_with_payload_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_shared()
    {
        return base.Can_update_many_to_many_shared();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_shared_unidirectional()
    {
        return base.Can_update_many_to_many_shared_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_shared_with_payload()
    {
        return base.Can_update_many_to_many_shared_with_payload();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_shared_with_payload_unidirectional()
    {
        return base.Can_update_many_to_many_shared_with_payload_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_with_inheritance()
    {
        return base.Can_update_many_to_many_with_inheritance();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_with_inheritance_unidirectional()
    {
        return base.Can_update_many_to_many_with_inheritance_unidirectional();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_with_navs()
    {
        return base.Can_update_many_to_many_with_navs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_update_many_to_many_with_payload()
    {
        return base.Can_update_many_to_many_with_payload();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Initial_tracking_uses_skip_navigations(bool async)
    {
        return base.Initial_tracking_uses_skip_navigations(async);
    }

}
