// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class ManyToManyTrackingCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_self_with_payload(bool async)
    {
        return base.Can_insert_many_to_many_self_with_payload(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_self_with_payload_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_self_with_payload_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_shared_with_payload(bool async)
    {
        return base.Can_insert_many_to_many_shared_with_payload(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_shared_with_payload_unidirectional(bool async)
    {
        return base.Can_insert_many_to_many_shared_with_payload_unidirectional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_insert_many_to_many_with_payload(bool async)
    {
        return base.Can_insert_many_to_many_with_payload(async);
    }

}
