// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class MaterializationInterceptionCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_query_materialization_with_owned_types(bool async, bool usePooling)
    {
        return base.Intercept_query_materialization_with_owned_types(async, usePooling);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_query_materialization_with_owned_types_projecting_collection(bool async, bool usePooling)
    {
        return base.Intercept_query_materialization_with_owned_types_projecting_collection(async, usePooling);
    }

}
