// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class MonsterFixupChangedOnlyCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_build_monster_model_and_seed_data_using_all_navigations()
    {
        return base.Can_build_monster_model_and_seed_data_using_all_navigations();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Can_build_monster_model_and_seed_data_using_dependent_navigations()
    {
        return base.Can_build_monster_model_and_seed_data_using_dependent_navigations();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_build_monster_model_and_seed_data_using_FKs()
    {
        return base.Can_build_monster_model_and_seed_data_using_FKs();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Can_build_monster_model_and_seed_data_using_navigations_with_deferred_add()
    {
        return base.Can_build_monster_model_and_seed_data_using_navigations_with_deferred_add();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Can_build_monster_model_and_seed_data_using_principal_navigations()
    {
        return base.Can_build_monster_model_and_seed_data_using_principal_navigations();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Composite_fixup_happens_when_FKs_change_test()
    {
        return base.Composite_fixup_happens_when_FKs_change_test();
    }

}
