// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class SaveChangesInterceptionCalciteTestBase
{

partial class SaveChangesInterceptionWithDiagnosticsCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_SaveChanges_failed(bool async, bool inject, bool noAcceptChanges, bool concurrencyError)
    {
        return base.Intercept_SaveChanges_failed(async, inject, noAcceptChanges, concurrencyError);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_SaveChanges_passively(bool async, bool inject, bool noAcceptChanges)
    {
        return base.Intercept_SaveChanges_passively(async, inject, noAcceptChanges);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_SaveChanges_to_change_result(bool async, bool inject, bool noAcceptChanges)
    {
        return base.Intercept_SaveChanges_to_change_result(async, inject, noAcceptChanges);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_SaveChanges_with_multiple_interceptors(bool async, bool inject, bool noAcceptChanges)
    {
        return base.Intercept_SaveChanges_with_multiple_interceptors(async, inject, noAcceptChanges);
    }

}

}
