// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class StoreGeneratedFixupCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_dep_uni_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_dep_uni_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_FK_not_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_FK_not_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_FK_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_FK_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_no_navs_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_no_navs_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_prin_uni_FK_not_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_prin_uni_FK_not_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_prin_uni_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_prin_uni_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_many_prin_uni_FK_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_many_prin_uni_FK_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_dep_uni_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_dep_uni_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_FK_not_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_FK_not_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_FK_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_FK_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_no_navs_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_no_navs_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_prin_uni_FK_not_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_prin_uni_FK_not_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_prin_uni_FK_set_no_navs_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_prin_uni_FK_set_no_navs_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_dependent_but_not_principal_one_to_one_prin_uni_FK_set_principal_nav_set()
    {
        return base.Add_dependent_but_not_principal_one_to_one_prin_uni_FK_set_principal_nav_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Multi_level_add_replace_and_save()
    {
        return base.Multi_level_add_replace_and_save();
    }

}
