// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class StoreGeneratedCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task After_save_ignore_ignores_value_even_if_modified(string propertyName, string expectedValue)
    {
        return base.After_save_ignore_ignores_value_even_if_modified(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task After_save_ignore_ignores_value_if_not_modified(string propertyName, string expectedValue)
    {
        return base.After_save_ignore_ignores_value_if_not_modified(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task After_save_throw_ignores_value_if_not_modified(string propertyName, string expectedValue)
    {
        return base.After_save_throw_ignores_value_if_not_modified(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task After_save_use_ignores_value_if_not_modified(string propertyName, string expectedValue)
    {
        return base.After_save_use_ignores_value_if_not_modified(propertyName, expectedValue);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_computed_property_on_Added_entity_with_default_value_gets_value_from_store()
    {
        return base.Always_computed_property_on_Added_entity_with_default_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_computed_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set()
    {
        return base.Always_computed_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_computed_property_on_Added_entity_with_temporary_value_gets_value_from_store()
    {
        return base.Always_computed_property_on_Added_entity_with_temporary_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_computed_property_on_Modified_entity_is_read_from_store_when_not_modified()
    {
        return base.Always_computed_property_on_Modified_entity_is_read_from_store_when_not_modified();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_computed_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state()
    {
        return base.Always_computed_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_identity_property_on_Added_entity_with_default_value_gets_value_from_store()
    {
        return base.Always_identity_property_on_Added_entity_with_default_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_identity_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set()
    {
        return base.Always_identity_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_identity_property_on_Added_entity_with_temporary_value_gets_value_from_store()
    {
        return base.Always_identity_property_on_Added_entity_with_temporary_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_identity_property_on_Modified_entity_is_not_included_in_the_update_when_not_modified()
    {
        return base.Always_identity_property_on_Modified_entity_is_not_included_in_the_update_when_not_modified();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Always_identity_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state()
    {
        return base.Always_identity_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Before_save_ignore_ignores_value_even_if_set(string propertyName, string expectedValue)
    {
        return base.Before_save_ignore_ignores_value_even_if_set(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Before_save_ignore_ignores_value_if_not_set(string propertyName, string expectedValue)
    {
        return base.Before_save_ignore_ignores_value_if_not_set(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Before_save_throw_ignores_value_if_not_set(string propertyName, string expectedValue)
    {
        return base.Before_save_throw_ignores_value_if_not_set(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Before_save_use_ignores_value_if_not_set(string propertyName, string expectedValue)
    {
        return base.Before_save_use_ignores_value_if_not_set(propertyName, expectedValue);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Change_state_of_entity_with_temp_non_key_does_not_throw(global::Microsoft.EntityFrameworkCore.EntityState targetState)
    {
        return base.Change_state_of_entity_with_temp_non_key_does_not_throw(targetState);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Clearing_optional_FK_does_not_leave_temporary_value()
    {
        return base.Clearing_optional_FK_does_not_leave_temporary_value();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Added_entity_can_have_value_set_explicitly()
    {
        return base.Computed_property_on_Added_entity_can_have_value_set_explicitly();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Added_entity_with_default_value_gets_value_from_store()
    {
        return base.Computed_property_on_Added_entity_with_default_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set()
    {
        return base.Computed_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Added_entity_with_temporary_value_gets_value_from_store()
    {
        return base.Computed_property_on_Added_entity_with_temporary_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Modified_entity_is_included_in_update_when_modified()
    {
        return base.Computed_property_on_Modified_entity_is_included_in_update_when_modified();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Modified_entity_is_read_from_store_when_not_modified()
    {
        return base.Computed_property_on_Modified_entity_is_read_from_store_when_not_modified();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Computed_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state()
    {
        return base.Computed_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Fields_used_correctly_for_store_generated_values()
    {
        return base.Fields_used_correctly_for_store_generated_values();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Added_entity_can_have_value_set_explicitly()
    {
        return base.Identity_property_on_Added_entity_can_have_value_set_explicitly();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Added_entity_with_default_value_gets_value_from_store()
    {
        return base.Identity_property_on_Added_entity_with_default_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set()
    {
        return base.Identity_property_on_Added_entity_with_read_only_before_save_throws_if_explicit_values_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Added_entity_with_temporary_value_gets_value_from_store()
    {
        return base.Identity_property_on_Added_entity_with_temporary_value_gets_value_from_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Added_entity_with_temporary_value_gets_value_from_store_even_if_same()
    {
        return base.Identity_property_on_Added_entity_with_temporary_value_gets_value_from_store_even_if_same();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Modified_entity_is_included_in_update_when_modified()
    {
        return base.Identity_property_on_Modified_entity_is_included_in_update_when_modified();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Modified_entity_is_not_included_in_update_when_not_modified()
    {
        return base.Identity_property_on_Modified_entity_is_not_included_in_update_when_not_modified();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Identity_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state()
    {
        return base.Identity_property_on_Modified_entity_with_read_only_after_save_throws_if_value_is_in_modified_state();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Insert_update_and_delete_with_StringAsGuid_key()
    {
        return base.Insert_update_and_delete_with_StringAsGuid_key();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Insert_update_and_delete_with_wrapped_Guid_key()
    {
        return base.Insert_update_and_delete_with_wrapped_Guid_key();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Nullable_fields_get_defaults_when_not_set()
    {
        return base.Nullable_fields_get_defaults_when_not_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Nullable_fields_store_any_value_when_set()
    {
        return base.Nullable_fields_store_any_value_when_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Nullable_fields_store_non_defaults_when_set()
    {
        return base.Nullable_fields_store_non_defaults_when_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Object_fields_get_defaults_when_not_set()
    {
        return base.Object_fields_get_defaults_when_not_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Object_fields_store_any_value_when_set()
    {
        return base.Object_fields_store_any_value_when_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Object_fields_store_non_defaults_when_set()
    {
        return base.Object_fields_store_non_defaults_when_set();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Properties_get_database_defaults_when_set_to_sentinel_values()
    {
        return base.Properties_get_database_defaults_when_set_to_sentinel_values();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Properties_get_set_values_when_not_set_to_sentinel_values()
    {
        return base.Properties_get_set_values_when_not_set_to_sentinel_values();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Store_generated_values_are_propagated_with_composite_key_cycles()
    {
        return base.Store_generated_values_are_propagated_with_composite_key_cycles();
    }

}
