// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class TransactionInterceptionCalciteTestBase
{

partial class TransactionInterceptionWithDiagnosticsCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task BeginTransaction_without_interceptor(bool async)
    {
        return base.BeginTransaction_without_interceptor(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_BeginTransaction(bool async)
    {
        return base.Intercept_BeginTransaction(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_BeginTransaction_to_suppress(bool async)
    {
        return base.Intercept_BeginTransaction_to_suppress(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_BeginTransaction_to_wrap(bool async)
    {
        return base.Intercept_BeginTransaction_to_wrap(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_BeginTransaction_with_isolation_level(bool async)
    {
        return base.Intercept_BeginTransaction_with_isolation_level(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_Commit(bool async)
    {
        return base.Intercept_Commit(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_Commit_to_suppress(bool async)
    {
        return base.Intercept_Commit_to_suppress(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_connection_with_multiple_interceptors(bool async)
    {
        return base.Intercept_connection_with_multiple_interceptors(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_CreateSavepoint(bool async)
    {
        return base.Intercept_CreateSavepoint(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_error_on_commit_or_rollback(bool async, bool commit)
    {
        return base.Intercept_error_on_commit_or_rollback(async, commit);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_ReleaseSavepoint(bool async)
    {
        return base.Intercept_ReleaseSavepoint(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_Rollback(bool async)
    {
        return base.Intercept_Rollback(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_Rollback_to_suppress(bool async)
    {
        return base.Intercept_Rollback_to_suppress(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_RollbackToSavepoint(bool async)
    {
        return base.Intercept_RollbackToSavepoint(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_UseTransaction(bool async)
    {
        return base.Intercept_UseTransaction(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Intercept_UseTransaction_to_wrap(bool async)
    {
        return base.Intercept_UseTransaction_to_wrap(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task UseTransaction_without_interceptor(bool async)
    {
        return base.UseTransaction_without_interceptor(async);
    }

}

}
