// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests;

partial class TwoDatabasesCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Can_query_from_one_connection_string_and_save_changes_to_another()
    {
        base.Can_query_from_one_connection_string_and_save_changes_to_another();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Can_set_connection_string_in_interceptor(bool withConnectionString, bool withNullConnectionString)
    {
        base.Can_set_connection_string_in_interceptor(withConnectionString, withNullConnectionString);
    }

}
