<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageProjectReference Include="..\Apache.Calcite.EntityFrameworkCore\Apache.Calcite.EntityFrameworkCore.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
        <PackageProjectReference Include="..\Apache.Calcite.EntityFrameworkCore.Core\Apache.Calcite.EntityFrameworkCore.Core.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
        <PackageProjectReference Include="..\Apache.Calcite.EntityFrameworkCore.Adapter\Apache.Calcite.EntityFrameworkCore.Adapter.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
    </ItemGroup>

</Project>
