using Microsoft.EntityFrameworkCore.Query.Associations.ComplexTableSplitting;

using Xunit.Abstractions;

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query.Associations.ComplexTableSplitting;

public partial class ComplexTableSplittingPrimitiveCollectionCalciteTest(ComplexTableSplittingCalciteFixture fixture, ITestOutputHelper testOutputHelper) :
    ComplexTableSplittingPrimitiveCollectionRelationalTestBase<ComplexTableSplittingCalciteFixture>(fixture, testOutputHelper);

