// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query.Associations.ComplexTableSplitting;

partial class ComplexTableSplittingBulkUpdateCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_another_associate()
    {
        return base.Update_associate_to_another_associate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_inline()
    {
        return base.Update_associate_to_inline();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_inline_with_lambda()
    {
        return base.Update_associate_to_inline_with_lambda();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_null()
    {
        return base.Update_associate_to_null();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_null_parameter()
    {
        return base.Update_associate_to_null_parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_null_with_lambda()
    {
        return base.Update_associate_to_null_with_lambda();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_to_parameter()
    {
        return base.Update_associate_to_parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_associate_with_null_required_property()
    {
        return base.Update_associate_with_null_required_property();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_collection_to_parameter()
    {
        return base.Update_collection_to_parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_inside_primitive_collection()
    {
        return base.Update_inside_primitive_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_multiple_projected_associates_via_anonymous_type()
    {
        return base.Update_multiple_projected_associates_via_anonymous_type();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_multiple_properties_inside_associates_and_on_entity_type()
    {
        return base.Update_multiple_properties_inside_associates_and_on_entity_type();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_multiple_properties_inside_same_associate()
    {
        return base.Update_multiple_properties_inside_same_associate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_nested_associate_to_another_nested_associate()
    {
        return base.Update_nested_associate_to_another_nested_associate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_nested_associate_to_inline_with_lambda()
    {
        return base.Update_nested_associate_to_inline_with_lambda();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_nested_associate_to_parameter()
    {
        return base.Update_nested_associate_to_parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_nested_collection_to_another_nested_collection()
    {
        return base.Update_nested_collection_to_another_nested_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_nested_collection_to_inline_with_lambda()
    {
        return base.Update_nested_collection_to_inline_with_lambda();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_nested_collection_to_parameter()
    {
        return base.Update_nested_collection_to_parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_primitive_collection_to_another_collection()
    {
        return base.Update_primitive_collection_to_another_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_primitive_collection_to_constant()
    {
        return base.Update_primitive_collection_to_constant();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_primitive_collection_to_parameter()
    {
        return base.Update_primitive_collection_to_parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_property_inside_associate()
    {
        return base.Update_property_inside_associate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_property_inside_associate_with_special_chars()
    {
        return base.Update_property_inside_associate_with_special_chars();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_property_inside_nested_associate()
    {
        return base.Update_property_inside_nested_associate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_property_on_projected_associate()
    {
        return base.Update_property_on_projected_associate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_property_on_projected_associate_with_OrderBy_Skip()
    {
        return base.Update_property_on_projected_associate_with_OrderBy_Skip();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_required_nested_associate_to_null()
    {
        return base.Update_required_nested_associate_to_null();
    }

}
