// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.GraphUpdates;

partial class ProxyGraphUpdatesCalciteTest
{

partial class ChangeTrackingAndLazyLoading
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Optional_many_to_one_dependents_are_orphaned_in_store(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Optional_many_to_one_dependents_are_orphaned_in_store(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Optional_many_to_one_dependents_with_alternate_key_are_orphaned_in_store(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Optional_many_to_one_dependents_with_alternate_key_are_orphaned_in_store(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Optional_one_to_one_relationships_are_one_to_one()
    {
        return base.Optional_one_to_one_relationships_are_one_to_one();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Optional_one_to_one_with_AK_relationships_are_one_to_one()
    {
        return base.Optional_one_to_one_with_AK_relationships_are_one_to_one();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_many_to_one_dependents_are_cascade_deleted_in_store(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_many_to_one_dependents_are_cascade_deleted_in_store(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_many_to_one_dependents_with_alternate_key_are_cascade_deleted_in_store(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_many_to_one_dependents_with_alternate_key_are_cascade_deleted_in_store(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_non_PK_one_to_one_are_cascade_detached_when_Added(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_non_PK_one_to_one_are_cascade_detached_when_Added(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_non_PK_one_to_one_with_alternate_key_are_cascade_detached_when_Added(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_non_PK_one_to_one_with_alternate_key_are_cascade_detached_when_Added(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_one_to_one_are_cascade_detached_when_Added(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_one_to_one_are_cascade_detached_when_Added(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_one_to_one_relationships_are_one_to_one()
    {
        return base.Required_one_to_one_relationships_are_one_to_one();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_one_to_one_with_AK_relationships_are_one_to_one()
    {
        return base.Required_one_to_one_with_AK_relationships_are_one_to_one();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_one_to_one_with_alternate_key_are_cascade_deleted_in_store(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_one_to_one_with_alternate_key_are_cascade_deleted_in_store(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Required_one_to_one_with_alternate_key_are_cascade_detached_when_Added(global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming cascadeDeleteTiming, global::Microsoft.EntityFrameworkCore.ChangeTracking.CascadeTiming deleteOrphansTiming)
    {
        return base.Required_one_to_one_with_alternate_key_are_cascade_detached_when_Added(cascadeDeleteTiming, deleteOrphansTiming);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Save_changed_optional_one_to_one_with_alternate_key_in_store()
    {
        return base.Save_changed_optional_one_to_one_with_alternate_key_in_store();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Save_two_entity_cycle_with_lazy_loading()
    {
        return base.Save_two_entity_cycle_with_lazy_loading();
    }

}

}
