// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class AdHocMiscellaneousQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Aggregate_over_subquery_in_group_by_projection(bool async)
    {
        return base.Aggregate_over_subquery_in_group_by_projection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Aggregate_over_subquery_in_group_by_projection_2(bool async)
    {
        return base.Aggregate_over_subquery_in_group_by_projection_2(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Enum_has_flag_does_not_apply_explicit_cast_for_non_constant()
    {
        return base.Enum_has_flag_does_not_apply_explicit_cast_for_non_constant();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Group_by_aggregate_in_subquery_projection_after_group_by(bool async)
    {
        return base.Group_by_aggregate_in_subquery_projection_after_group_by(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Query_when_null_key_in_database_should_throw()
    {
        return base.Query_when_null_key_in_database_should_throw();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task StoreType_for_UDF_used(bool async)
    {
        return base.StoreType_for_UDF_used(async);
    }

}
