// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class AdHocQuerySplittingQueryCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_async()
    {
        return base.Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_async();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_sync()
    {
        return base.Can_query_with_nav_collection_in_projection_with_split_query_in_parallel_sync();
    }

}
