// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class AdHocJsonQueryCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_project_nullable_json_property_when_the_element_in_json_is_not_present()
    {
        return base.Can_project_nullable_json_property_when_the_element_in_json_is_not_present();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Contains_on_nested_collection_with_init_only_navigation()
    {
        return base.Contains_on_nested_collection_with_init_only_navigation();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task HasJsonPropertyName()
    {
        return base.HasJsonPropertyName();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Optional_json_properties_materialized_as_null_when_the_element_in_json_is_not_present()
    {
        return base.Optional_json_properties_materialized_as_null_when_the_element_in_json_is_not_present();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Predicate_based_on_element_of_json_array_of_primitives1()
    {
        return base.Predicate_based_on_element_of_json_array_of_primitives1();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Predicate_based_on_element_of_json_array_of_primitives2()
    {
        return base.Predicate_based_on_element_of_json_array_of_primitives2();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Predicate_based_on_element_of_json_array_of_primitives3()
    {
        return base.Predicate_based_on_element_of_json_array_of_primitives3();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_element_of_json_array_of_primitives()
    {
        return base.Project_element_of_json_array_of_primitives();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_json_array_of_primitives_on_reference()
    {
        return base.Project_json_array_of_primitives_on_reference();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_missing_required_navigation(bool async)
    {
        return base.Project_missing_required_navigation(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_missing_required_scalar(bool async)
    {
        return base.Project_missing_required_scalar(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_nested_json_entity_with_missing_scalars(bool async)
    {
        return base.Project_nested_json_entity_with_missing_scalars(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_null_required_navigation(bool async)
    {
        return base.Project_null_required_navigation(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_null_required_scalar(bool async)
    {
        return base.Project_null_required_scalar(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_root_entity_with_missing_required_navigation(bool async)
    {
        return base.Project_root_entity_with_missing_required_navigation(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_root_entity_with_null_required_navigation(bool async)
    {
        return base.Project_root_entity_with_null_required_navigation(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_root_with_missing_scalars(bool async)
    {
        return base.Project_root_with_missing_scalars(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_top_level_entity_with_null_value_required_scalars(bool async)
    {
        return base.Project_top_level_entity_with_null_value_required_scalars(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_top_level_json_entity_with_missing_scalars(bool async)
    {
        return base.Project_top_level_json_entity_with_missing_scalars(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Try_project_collection_but_JSON_is_entity()
    {
        return base.Try_project_collection_but_JSON_is_entity();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Try_project_reference_but_JSON_is_collection()
    {
        return base.Try_project_reference_but_JSON_is_collection();
    }

}
