// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class ComplexTypeQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Filter_on_property_inside_complex_type_after_subquery(bool async)
    {
        return base.Filter_on_property_inside_complex_type_after_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Filter_on_property_inside_nested_complex_type_after_subquery(bool async)
    {
        return base.Filter_on_property_inside_nested_complex_type_after_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_same_nested_complex_type_twice_with_double_pushdown(bool async)
    {
        return base.Project_same_nested_complex_type_twice_with_double_pushdown(async);
    }

}
