// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class EntitySplittingQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_entity_which_is_split_in_three(bool async)
    {
        return base.Can_query_entity_which_is_split_in_three(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_entity_which_is_split_in_two(bool async)
    {
        return base.Can_query_entity_which_is_split_in_two(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_entity_which_is_split_selecting_only_main_properties(bool async)
    {
        return base.Can_query_entity_which_is_split_selecting_only_main_properties(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_entity_which_is_split_selecting_only_part_2_properties(bool async)
    {
        return base.Can_query_entity_which_is_split_selecting_only_part_2_properties(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_query_entity_which_is_split_selecting_only_part_3_properties(bool async)
    {
        return base.Can_query_entity_which_is_split_selecting_only_part_3_properties(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Compare_split_entity_to_null(bool async)
    {
        return base.Compare_split_entity_to_null(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Custom_projection_trim_when_multiple_tables(bool async)
    {
        return base.Custom_projection_trim_when_multiple_tables(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Include_collection_on_split_entity(bool async)
    {
        return base.Include_collection_on_split_entity(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Include_collection_to_split_entity(bool async)
    {
        return base.Include_collection_to_split_entity(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Include_collection_to_split_entity_including_collection(bool async)
    {
        return base.Include_collection_to_split_entity_including_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Include_reference_on_split_entity(bool async)
    {
        return base.Include_reference_on_split_entity(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Include_reference_to_split_entity(bool async)
    {
        return base.Include_reference_to_split_entity(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Include_reference_to_split_entity_including_reference(bool async)
    {
        return base.Include_reference_to_split_entity_including_reference(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Normal_entity_owning_a_split_collection(bool async)
    {
        return base.Normal_entity_owning_a_split_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Normal_entity_owning_a_split_reference_with_main_fragment_not_sharing(bool async)
    {
        return base.Normal_entity_owning_a_split_reference_with_main_fragment_not_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Normal_entity_owning_a_split_reference_with_main_fragment_not_sharing_custom_projection(bool async)
    {
        return base.Normal_entity_owning_a_split_reference_with_main_fragment_not_sharing_custom_projection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Normal_entity_owning_a_split_reference_with_main_fragment_sharing(bool async)
    {
        return base.Normal_entity_owning_a_split_reference_with_main_fragment_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Normal_entity_owning_a_split_reference_with_main_fragment_sharing_custom_projection(bool async)
    {
        return base.Normal_entity_owning_a_split_reference_with_main_fragment_sharing_custom_projection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Normal_entity_owning_a_split_reference_with_main_fragment_sharing_multiple_level(bool async)
    {
        return base.Normal_entity_owning_a_split_reference_with_main_fragment_sharing_multiple_level(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_collection(bool async)
    {
        return base.Split_entity_owning_a_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_reference(bool async)
    {
        return base.Split_entity_owning_a_reference(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_split_collection(bool async)
    {
        return base.Split_entity_owning_a_split_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_split_reference_with_table_sharing_1(bool async)
    {
        return base.Split_entity_owning_a_split_reference_with_table_sharing_1(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_split_reference_with_table_sharing_4(bool async)
    {
        return base.Split_entity_owning_a_split_reference_with_table_sharing_4(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_split_reference_with_table_sharing_6(bool async)
    {
        return base.Split_entity_owning_a_split_reference_with_table_sharing_6(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Split_entity_owning_a_split_reference_without_table_sharing(bool async)
    {
        return base.Split_entity_owning_a_split_reference_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_collection_on_base(bool async)
    {
        return base.Tpc_entity_owning_a_split_collection_on_base(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_collection_on_leaf(bool async)
    {
        return base.Tpc_entity_owning_a_split_collection_on_leaf(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_collection_on_middle(bool async)
    {
        return base.Tpc_entity_owning_a_split_collection_on_middle(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_reference_on_base_without_table_sharing(bool async)
    {
        return base.Tpc_entity_owning_a_split_reference_on_base_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_reference_on_leaf_with_table_sharing(bool async)
    {
        return base.Tpc_entity_owning_a_split_reference_on_leaf_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_reference_on_leaf_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tpc_entity_owning_a_split_reference_on_leaf_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_reference_on_leaf_without_table_sharing(bool async)
    {
        return base.Tpc_entity_owning_a_split_reference_on_leaf_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpc_entity_owning_a_split_reference_on_middle_without_table_sharing(bool async)
    {
        return base.Tpc_entity_owning_a_split_reference_on_middle_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_collection_on_base(bool async)
    {
        return base.Tph_entity_owning_a_split_collection_on_base(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_collection_on_leaf(bool async)
    {
        return base.Tph_entity_owning_a_split_collection_on_leaf(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_collection_on_middle(bool async)
    {
        return base.Tph_entity_owning_a_split_collection_on_middle(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_base_with_table_sharing(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_base_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_base_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_base_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_base_without_table_sharing(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_base_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_leaf_with_table_sharing(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_leaf_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_leaf_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_leaf_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_leaf_without_table_sharing(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_leaf_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_middle_with_table_sharing(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_middle_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_middle_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_middle_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tph_entity_owning_a_split_reference_on_middle_without_table_sharing(bool async)
    {
        return base.Tph_entity_owning_a_split_reference_on_middle_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_collection_on_base(bool async)
    {
        return base.Tpt_entity_owning_a_split_collection_on_base(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_collection_on_leaf(bool async)
    {
        return base.Tpt_entity_owning_a_split_collection_on_leaf(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_collection_on_middle(bool async)
    {
        return base.Tpt_entity_owning_a_split_collection_on_middle(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_base_with_table_sharing(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_base_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_base_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_base_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_base_without_table_sharing(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_base_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_leaf_with_table_sharing(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_leaf_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_leaf_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_leaf_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_leaf_without_table_sharing(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_leaf_without_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_middle_with_table_sharing(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_middle_with_table_sharing(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_middle_with_table_sharing_querying_sibling(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_middle_with_table_sharing_querying_sibling(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Tpt_entity_owning_a_split_reference_on_middle_without_table_sharing(bool async)
    {
        return base.Tpt_entity_owning_a_split_reference_on_middle_without_table_sharing(async);
    }

}
