// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class FunkyDataQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_contains_on_argument_with_wildcard_column(bool async)
    {
        return base.String_contains_on_argument_with_wildcard_column(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_contains_on_argument_with_wildcard_column_negated(bool async)
    {
        return base.String_contains_on_argument_with_wildcard_column_negated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_contains_on_argument_with_wildcard_constant(bool async)
    {
        return base.String_contains_on_argument_with_wildcard_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_contains_on_argument_with_wildcard_parameter(bool async)
    {
        return base.String_contains_on_argument_with_wildcard_parameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_equals_nullable_column(bool async)
    {
        return base.String_ends_with_equals_nullable_column(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_inside_conditional(bool async)
    {
        return base.String_ends_with_inside_conditional(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_inside_conditional_negated(bool async)
    {
        return base.String_ends_with_inside_conditional_negated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_not_equals_nullable_column(bool async)
    {
        return base.String_ends_with_not_equals_nullable_column(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_on_argument_with_wildcard_column(bool async)
    {
        return base.String_ends_with_on_argument_with_wildcard_column(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_on_argument_with_wildcard_column_negated(bool async)
    {
        return base.String_ends_with_on_argument_with_wildcard_column_negated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_on_argument_with_wildcard_constant(bool async)
    {
        return base.String_ends_with_on_argument_with_wildcard_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_ends_with_on_argument_with_wildcard_parameter(bool async)
    {
        return base.String_ends_with_on_argument_with_wildcard_parameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_FirstOrDefault_and_LastOrDefault(bool async)
    {
        return base.String_FirstOrDefault_and_LastOrDefault(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_starts_with_on_argument_with_bracket(bool async)
    {
        return base.String_starts_with_on_argument_with_bracket(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_starts_with_on_argument_with_wildcard_column(bool async)
    {
        return base.String_starts_with_on_argument_with_wildcard_column(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_starts_with_on_argument_with_wildcard_column_negated(bool async)
    {
        return base.String_starts_with_on_argument_with_wildcard_column_negated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_starts_with_on_argument_with_wildcard_constant(bool async)
    {
        return base.String_starts_with_on_argument_with_wildcard_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_starts_with_on_argument_with_wildcard_parameter(bool async)
    {
        return base.String_starts_with_on_argument_with_wildcard_parameter(async);
    }

}
