// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NonSharedPrimitiveCollectionsQueryCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Array_of_byte_array()
    {
        return base.Array_of_byte_array();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Array_of_DateTime_with_microseconds()
    {
        return base.Array_of_DateTime_with_microseconds();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Array_of_enum()
    {
        return base.Array_of_enum();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_inside_json_owned_entity()
    {
        return base.Column_collection_inside_json_owned_entity();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_Contains_with_default_mode_EF_Parameter(global::Microsoft.EntityFrameworkCore.ParameterTranslationMode mode)
    {
        return base.Parameter_collection_Contains_with_default_mode_EF_Parameter(mode);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_Count_with_column_predicate_with_default_mode(global::Microsoft.EntityFrameworkCore.ParameterTranslationMode mode)
    {
        return base.Parameter_collection_Count_with_column_predicate_with_default_mode(mode);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_Count_with_column_predicate_with_default_mode_EF_Parameter(global::Microsoft.EntityFrameworkCore.ParameterTranslationMode mode)
    {
        return base.Parameter_collection_Count_with_column_predicate_with_default_mode_EF_Parameter(mode);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_of_enum_Cast_from_different_enum_type(global::Microsoft.EntityFrameworkCore.ParameterTranslationMode mode)
    {
        return base.Parameter_collection_of_enum_Cast_from_different_enum_type(mode);
    }

}
