// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NorthwindKeylessEntitiesQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Entity_mapped_to_view_on_right_side_of_join(bool async)
    {
        return base.Entity_mapped_to_view_on_right_side_of_join(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task KeylessEntity_by_database_view(bool async)
    {
        return base.KeylessEntity_by_database_view(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task KeylessEntity_groupby(bool async)
    {
        return base.KeylessEntity_groupby(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task KeylessEntity_with_defining_query_and_correlated_collection(bool async)
    {
        return base.KeylessEntity_with_defining_query_and_correlated_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task KeylessEntity_with_included_navs_multi_level(bool async)
    {
        return base.KeylessEntity_with_included_navs_multi_level(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task KeylessEntity_with_nav_defining_query(bool async)
    {
        return base.KeylessEntity_with_nav_defining_query(async);
    }

}
