// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NorthwindSelectQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Collection_projection_selecting_outer_element_followed_by_take(bool async)
    {
        return base.Collection_projection_selecting_outer_element_followed_by_take(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Correlated_collection_after_distinct_with_complex_projection_not_containing_original_identifier(bool async)
    {
        return base.Correlated_collection_after_distinct_with_complex_projection_not_containing_original_identifier(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Correlated_collection_after_groupby_with_complex_projection_containing_original_identifier(bool async)
    {
        return base.Correlated_collection_after_groupby_with_complex_projection_containing_original_identifier(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Correlated_collection_after_groupby_with_complex_projection_not_containing_original_identifier(bool async)
    {
        return base.Correlated_collection_after_groupby_with_complex_projection_not_containing_original_identifier(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Member_binding_after_ctor_arguments_fails_with_client_eval(bool async)
    {
        return base.Member_binding_after_ctor_arguments_fails_with_client_eval(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_keyless_entity_FirstOrDefault_without_orderby(bool async)
    {
        return base.Project_keyless_entity_FirstOrDefault_without_orderby(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_single_element_from_collection_with_OrderBy_Take_and_FirstOrDefault_with_parameter(bool async)
    {
        return base.Project_single_element_from_collection_with_OrderBy_Take_and_FirstOrDefault_with_parameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Projecting_after_navigation_and_distinct(bool async)
    {
        return base.Projecting_after_navigation_and_distinct(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Projection_containing_DateTime_subtraction(bool async)
    {
        return base.Projection_containing_DateTime_subtraction(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Projection_when_arithmetic_mixed_subqueries(bool async)
    {
        return base.Projection_when_arithmetic_mixed_subqueries(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Reverse_without_explicit_ordering(bool async)
    {
        return base.Reverse_without_explicit_ordering(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_bool_closure_with_order_by_property_with_cast_to_nullable(bool async)
    {
        return base.Select_bool_closure_with_order_by_property_with_cast_to_nullable(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection(bool async)
    {
        return base.Select_nested_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection_deep(bool async)
    {
        return base.Select_nested_collection_deep(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection_deep_distinct_no_identifiers(bool async)
    {
        return base.Select_nested_collection_deep_distinct_no_identifiers(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection_multi_level5(bool async)
    {
        return base.Select_nested_collection_multi_level5(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection_multi_level6(bool async)
    {
        return base.Select_nested_collection_multi_level6(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_short_constant(bool async)
    {
        return base.Select_short_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_with_complex_expression_that_can_be_funcletized(bool async)
    {
        return base.Select_with_complex_expression_that_can_be_funcletized(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_with_multiple_Take(bool async)
    {
        return base.Select_with_multiple_Take(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SelectMany_with_collection_being_correlated_subquery_which_references_inner_and_outer_entity(bool async)
    {
        return base.SelectMany_with_collection_being_correlated_subquery_which_references_inner_and_outer_entity(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SelectMany_with_collection_being_correlated_subquery_which_references_non_mapped_properties_from_inner_and_outer_entity(bool async)
    {
        return base.SelectMany_with_collection_being_correlated_subquery_which_references_non_mapped_properties_from_inner_and_outer_entity(async);
    }

}
