// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NorthwindAggregateOperatorsQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Average_over_max_subquery(bool async)
    {
        return base.Average_over_max_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Average_over_nested_subquery(bool async)
    {
        return base.Average_over_nested_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Contains_inside_Average_without_GroupBy(bool async)
    {
        return base.Contains_inside_Average_without_GroupBy(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Contains_inside_LongCount_without_GroupBy(bool async)
    {
        return base.Contains_inside_LongCount_without_GroupBy(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Contains_with_local_anonymous_type_array_closure(bool async)
    {
        return base.Contains_with_local_anonymous_type_array_closure(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Contains_with_local_tuple_array_closure(bool async)
    {
        return base.Contains_with_local_tuple_array_closure(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task String_FirstOrDefault_in_projection_does_not_do_client_eval(bool async)
    {
        return base.String_FirstOrDefault_in_projection_does_not_do_client_eval(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Sum_over_uncorrelated_subquery(bool async)
    {
        return base.Sum_over_uncorrelated_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Type_casting_inside_sum(bool async)
    {
        return base.Type_casting_inside_sum(async);
    }

}
