// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NorthwindWhereQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Skip_and_Where_evaluation_order(bool async)
    {
        return base.Skip_and_Where_evaluation_order(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Take_and_Where_evaluation_order(bool async)
    {
        return base.Take_and_Where_evaluation_order(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_constructed_equal(bool async)
    {
        return base.Where_compare_constructed_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_constructed_multi_value_equal(bool async)
    {
        return base.Where_compare_constructed_multi_value_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_constructed_multi_value_not_equal(bool async)
    {
        return base.Where_compare_constructed_multi_value_not_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_tuple_constructed_equal(bool async)
    {
        return base.Where_compare_tuple_constructed_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_tuple_constructed_multi_value_equal(bool async)
    {
        return base.Where_compare_tuple_constructed_multi_value_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_tuple_constructed_multi_value_not_equal(bool async)
    {
        return base.Where_compare_tuple_constructed_multi_value_not_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_tuple_create_constructed_equal(bool async)
    {
        return base.Where_compare_tuple_create_constructed_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_tuple_create_constructed_multi_value_equal(bool async)
    {
        return base.Where_compare_tuple_create_constructed_multi_value_equal(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_compare_tuple_create_constructed_multi_value_not_equal(bool async)
    {
        return base.Where_compare_tuple_create_constructed_multi_value_not_equal(async);
    }

}
