// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NorthwindGroupByQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Complex_query_with_groupBy_in_subquery4(bool async)
    {
        return base.Complex_query_with_groupBy_in_subquery4(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_aggregate_followed_another_GroupBy_aggregate(bool async)
    {
        return base.GroupBy_aggregate_followed_another_GroupBy_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_aggregate_from_multiple_query_in_same_projection_2(bool async)
    {
        return base.GroupBy_aggregate_from_multiple_query_in_same_projection_2(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_aggregate_join_another_GroupBy_aggregate(bool async)
    {
        return base.GroupBy_aggregate_join_another_GroupBy_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_anonymous_key_type_mismatch_with_aggregate(bool async)
    {
        return base.GroupBy_anonymous_key_type_mismatch_with_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_anonymous_Select_LongCount(bool async)
    {
        return base.GroupBy_anonymous_Select_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_complex_key_aggregate_2(bool async)
    {
        return base.GroupBy_complex_key_aggregate_2(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Composite_Select_Key_LongCount(bool async)
    {
        return base.GroupBy_Composite_Select_Key_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Composite_Select_LongCount(bool async)
    {
        return base.GroupBy_Composite_Select_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_constant_with_where_on_grouping_with_aggregate_operators(bool async)
    {
        return base.GroupBy_constant_with_where_on_grouping_with_aggregate_operators(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Dto_as_element_selector_Select_Sum(bool async)
    {
        return base.GroupBy_Dto_as_element_selector_Select_Sum(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Property_anonymous_element_selector_LongCount(bool async)
    {
        return base.GroupBy_Property_anonymous_element_selector_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Property_scalar_element_selector_LongCount(bool async)
    {
        return base.GroupBy_Property_scalar_element_selector_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Property_Select_Key_LongCount(bool async)
    {
        return base.GroupBy_Property_Select_Key_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Property_Select_LongCount(bool async)
    {
        return base.GroupBy_Property_Select_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Property_Select_LongCount_with_nulls(bool async)
    {
        return base.GroupBy_Property_Select_LongCount_with_nulls(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Property_Select_LongCount_with_predicate(bool async)
    {
        return base.GroupBy_Property_Select_LongCount_with_predicate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Select_Distinct_aggregate(bool async)
    {
        return base.GroupBy_Select_Distinct_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_select_grouping_composed_list(bool async)
    {
        return base.GroupBy_select_grouping_composed_list(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Sum_constant_cast(bool async)
    {
        return base.GroupBy_Sum_constant_cast(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Where_Count_with_predicate(bool async)
    {
        return base.GroupBy_Where_Count_with_predicate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Where_LongCount(bool async)
    {
        return base.GroupBy_Where_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Where_Select_Where_Count(bool async)
    {
        return base.GroupBy_Where_Select_Where_Count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Where_Select_Where_Select_Min(bool async)
    {
        return base.GroupBy_Where_Select_Where_Select_Min(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Where_Sum(bool async)
    {
        return base.GroupBy_Where_Sum(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_Where_Where_Count(bool async)
    {
        return base.GroupBy_Where_Where_Count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_with_aggregate_containing_complex_where(bool async)
    {
        return base.GroupBy_with_aggregate_containing_complex_where(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_with_group_key_being_nested_navigation(bool async)
    {
        return base.GroupBy_with_group_key_being_nested_navigation(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy_with_grouping_key_DateTime_Day(bool async)
    {
        return base.GroupBy_with_grouping_key_DateTime_Day(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Join_GroupBy_Aggregate_distinct_single_join(bool async)
    {
        return base.Join_GroupBy_Aggregate_distinct_single_join(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task LongCount_after_GroupBy_aggregate(bool async)
    {
        return base.LongCount_after_GroupBy_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task LongCount_after_GroupBy_without_aggregate(bool async)
    {
        return base.LongCount_after_GroupBy_without_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task LongCount_with_predicate_after_GroupBy_without_aggregate(bool async)
    {
        return base.LongCount_with_predicate_after_GroupBy_without_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_select_function_groupby_followed_by_another_select_with_aggregates(bool async)
    {
        return base.Where_select_function_groupby_followed_by_another_select_with_aggregates(async);
    }

}
