// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class NorthwindMiscellaneousQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task All_top_level_subquery(bool async)
    {
        return base.All_top_level_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task All_top_level_subquery_ef_property(bool async)
    {
        return base.All_top_level_subquery_ef_property(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Anonymous_subquery_orderby(bool async)
    {
        return base.Anonymous_subquery_orderby(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task AsQueryable_in_query_server_evals(bool async)
    {
        return base.AsQueryable_in_query_server_evals(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Client_code_unknown_method(bool async)
    {
        return base.Client_code_unknown_method(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Client_code_using_instance_in_anonymous_type(bool async)
    {
        return base.Client_code_using_instance_in_anonymous_type(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Client_code_using_instance_in_static_method(bool async)
    {
        return base.Client_code_using_instance_in_static_method(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Client_code_using_instance_method_throws(bool async)
    {
        return base.Client_code_using_instance_method_throws(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Complex_query_with_repeated_nested_query_model_compiles_correctly(bool async)
    {
        return base.Complex_query_with_repeated_nested_query_model_compiles_correctly(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Contains_with_DateTime_Date(bool async)
    {
        return base.Contains_with_DateTime_Date(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task DTO_subquery_orderby(bool async)
    {
        return base.DTO_subquery_orderby(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Entity_equality_orderby_subquery(bool async)
    {
        return base.Entity_equality_orderby_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Entity_equality_through_subquery_composite_key(bool async)
    {
        return base.Entity_equality_through_subquery_composite_key(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Handle_materialization_properly_when_more_than_two_query_sources_are_involved(bool async)
    {
        return base.Handle_materialization_properly_when_more_than_two_query_sources_are_involved(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Max_on_empty_sequence_throws(bool async)
    {
        return base.Max_on_empty_sequence_throws(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task OrderBy_correlated_subquery2(bool async)
    {
        return base.OrderBy_correlated_subquery2(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task OrderBy_skip_take_take(bool async)
    {
        return base.OrderBy_skip_take_take(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task OrderBy_skip_take_take_take_take(bool async)
    {
        return base.OrderBy_skip_take_take_take_take(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_extraction_short_circuits_1(bool async)
    {
        return base.Parameter_extraction_short_circuits_1(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_extraction_short_circuits_2(bool async)
    {
        return base.Parameter_extraction_short_circuits_2(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_extraction_short_circuits_3(bool async)
    {
        return base.Parameter_extraction_short_circuits_3(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_distinct_long_count(bool async)
    {
        return base.Select_distinct_long_count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_distinct_Select_with_client_bindings(bool async)
    {
        return base.Select_distinct_Select_with_client_bindings(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_expression_references_are_updated_correctly_with_subquery(bool async)
    {
        return base.Select_expression_references_are_updated_correctly_with_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection_in_anonymous_type(bool async)
    {
        return base.Select_nested_collection_in_anonymous_type(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_orderBy_skip_long_count(bool async)
    {
        return base.Select_orderBy_skip_long_count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_orderBy_take_long_count(bool async)
    {
        return base.Select_orderBy_take_long_count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_skip_long_count(bool async)
    {
        return base.Select_skip_long_count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_take_long_count(bool async)
    {
        return base.Select_take_long_count(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SelectMany_LongCount(bool async)
    {
        return base.SelectMany_LongCount(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Subquery_with_navigation_inside_inline_collection(bool async)
    {
        return base.Subquery_with_navigation_inside_inline_collection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Take_with_single(bool async)
    {
        return base.Take_with_single(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Take_with_single_select_many(bool async)
    {
        return base.Take_with_single_select_many(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Using_static_string_Equals_with_StringComparison_throws_informative_error(bool async)
    {
        return base.Using_static_string_Equals_with_StringComparison_throws_informative_error(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Using_string_Equals_with_StringComparison_throws_informative_error(bool async)
    {
        return base.Using_string_Equals_with_StringComparison_throws_informative_error(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Where_nanosecond_and_microsecond_component(bool async)
    {
        return base.Where_nanosecond_and_microsecond_component(async);
    }

}
