// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class PrimitiveCollectionsQueryCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_in_subquery_Union_parameter_collection()
    {
        return base.Column_collection_in_subquery_Union_parameter_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Contains_with_EF_Parameter()
    {
        return base.Inline_collection_Contains_with_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Contains_with_IEnumerable_EF_Parameter()
    {
        return base.Inline_collection_Contains_with_IEnumerable_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Count_with_column_predicate_with_EF_Parameter()
    {
        return base.Inline_collection_Count_with_column_predicate_with_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_index_Column()
    {
        return base.Inline_collection_index_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_index_Column_with_EF_Constant()
    {
        return base.Inline_collection_index_Column_with_EF_Constant();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_List_value_index_Column()
    {
        return base.Inline_collection_List_value_index_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_value_index_Column()
    {
        return base.Inline_collection_value_index_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_empty_Join()
    {
        return base.Parameter_collection_empty_Join();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_index_Column_equal_Column()
    {
        return base.Parameter_collection_index_Column_equal_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_index_Column_equal_constant()
    {
        return base.Parameter_collection_index_Column_equal_constant();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_of_nullable_ints_Contains_nullable_int_with_EF_Parameter()
    {
        return base.Parameter_collection_of_nullable_ints_Contains_nullable_int_with_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_with_type_inference_for_JsonScalarExpression()
    {
        return base.Parameter_collection_with_type_inference_for_JsonScalarExpression();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_collection_of_datetimes_filtered()
    {
        return base.Project_collection_of_datetimes_filtered();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_multiple_collections()
    {
        return base.Project_multiple_collections();
    }

}
