// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class PrimitiveCollectionsQueryCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Any()
    {
        return base.Column_collection_Any();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Contains_over_subquery()
    {
        return base.Column_collection_Contains_over_subquery();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Count_method()
    {
        return base.Column_collection_Count_method();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Count_with_predicate()
    {
        return base.Column_collection_Count_with_predicate();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Distinct()
    {
        return base.Column_collection_Distinct();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_ElementAt()
    {
        return base.Column_collection_ElementAt();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_First()
    {
        return base.Column_collection_First();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_FirstOrDefault()
    {
        return base.Column_collection_FirstOrDefault();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_in_subquery_Union_parameter_collection()
    {
        return base.Column_collection_in_subquery_Union_parameter_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_index_beyond_end()
    {
        return base.Column_collection_index_beyond_end();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_index_datetime()
    {
        return base.Column_collection_index_datetime();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_index_int()
    {
        return base.Column_collection_index_int();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_index_string()
    {
        return base.Column_collection_index_string();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Intersect_inline_collection()
    {
        return base.Column_collection_Intersect_inline_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Join_parameter_collection()
    {
        return base.Column_collection_Join_parameter_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Length()
    {
        return base.Column_collection_Length();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_of_bools_Contains()
    {
        return base.Column_collection_of_bools_Contains();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_of_ints_Contains()
    {
        return base.Column_collection_of_ints_Contains();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_of_nullable_ints_Contains()
    {
        return base.Column_collection_of_nullable_ints_Contains();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_of_nullable_ints_Contains_null()
    {
        return base.Column_collection_of_nullable_ints_Contains_null();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_of_nullable_strings_contains_null()
    {
        return base.Column_collection_of_nullable_strings_contains_null();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_of_strings_contains_null()
    {
        return base.Column_collection_of_strings_contains_null();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_OrderByDescending_ElementAt()
    {
        return base.Column_collection_OrderByDescending_ElementAt();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_SelectMany()
    {
        return base.Column_collection_SelectMany();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_SelectMany_with_filter()
    {
        return base.Column_collection_SelectMany_with_filter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_SelectMany_with_Select_to_anonymous_type()
    {
        return base.Column_collection_SelectMany_with_Select_to_anonymous_type();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Single()
    {
        return base.Column_collection_Single();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_SingleOrDefault()
    {
        return base.Column_collection_SingleOrDefault();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Skip()
    {
        return base.Column_collection_Skip();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Skip_Take()
    {
        return base.Column_collection_Skip_Take();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Take()
    {
        return base.Column_collection_Take();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Union_parameter_collection()
    {
        return base.Column_collection_Union_parameter_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Where_Count()
    {
        return base.Column_collection_Where_Count();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Where_ElementAt()
    {
        return base.Column_collection_Where_ElementAt();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Where_Skip()
    {
        return base.Column_collection_Where_Skip();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Where_Skip_Take()
    {
        return base.Column_collection_Where_Skip_Take();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Where_Take()
    {
        return base.Column_collection_Where_Take();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Column_collection_Where_Union()
    {
        return base.Column_collection_Where_Union();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Contains_with_EF_Parameter()
    {
        return base.Inline_collection_Contains_with_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Contains_with_IEnumerable_EF_Parameter()
    {
        return base.Inline_collection_Contains_with_IEnumerable_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Count_with_column_predicate_with_EF_Parameter()
    {
        return base.Inline_collection_Count_with_column_predicate_with_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Except_column_collection()
    {
        return base.Inline_collection_Except_column_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_index_Column()
    {
        return base.Inline_collection_index_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_index_Column_with_EF_Constant()
    {
        return base.Inline_collection_index_Column_with_EF_Constant();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_Join_ordered_column_collection()
    {
        return base.Inline_collection_Join_ordered_column_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_List_value_index_Column()
    {
        return base.Inline_collection_List_value_index_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Inline_collection_value_index_Column()
    {
        return base.Inline_collection_value_index_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Non_nullable_reference_column_collection_index_equals_nullable_column()
    {
        return base.Non_nullable_reference_column_collection_index_equals_nullable_column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Nullable_reference_column_collection_index_equals_nullable_column()
    {
        return base.Nullable_reference_column_collection_index_equals_nullable_column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_Concat_column_collection()
    {
        return base.Parameter_collection_Concat_column_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_empty_Join()
    {
        return base.Parameter_collection_empty_Join();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_in_subquery_Union_column_collection()
    {
        return base.Parameter_collection_in_subquery_Union_column_collection();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_in_subquery_Union_column_collection_as_compiled_query()
    {
        return base.Parameter_collection_in_subquery_Union_column_collection_as_compiled_query();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_in_subquery_Union_column_collection_nested()
    {
        return base.Parameter_collection_in_subquery_Union_column_collection_nested();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_index_Column_equal_Column()
    {
        return base.Parameter_collection_index_Column_equal_Column();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_index_Column_equal_constant()
    {
        return base.Parameter_collection_index_Column_equal_constant();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_of_nullable_ints_Contains_nullable_int_with_EF_Parameter()
    {
        return base.Parameter_collection_of_nullable_ints_Contains_nullable_int_with_EF_Parameter();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Parameter_collection_with_type_inference_for_JsonScalarExpression()
    {
        return base.Parameter_collection_with_type_inference_for_JsonScalarExpression();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_collection_of_datetimes_filtered()
    {
        return base.Project_collection_of_datetimes_filtered();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_collection_of_ints_ordered()
    {
        return base.Project_collection_of_ints_ordered();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_collection_of_nullable_ints_with_paging2()
    {
        return base.Project_collection_of_nullable_ints_with_paging2();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_empty_collection_of_nullables_and_collection_only_containing_nulls()
    {
        return base.Project_empty_collection_of_nullables_and_collection_only_containing_nulls();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Project_multiple_collections()
    {
        return base.Project_multiple_collections();
    }

}
