// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class QueryFilterFuncletizationCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override void Using_multiple_entities_with_filters_reuses_parameters()
    {
        base.Using_multiple_entities_with_filters_reuses_parameters();
    }

}
