// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query;

partial class SqlQueryCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Bad_data_error_handling_null(bool async)
    {
        return base.Bad_data_error_handling_null(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Bad_data_error_handling_null_no_tracking(bool async)
    {
        return base.Bad_data_error_handling_null_no_tracking(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Bad_data_error_handling_null_projection(bool async)
    {
        return base.Bad_data_error_handling_null_projection(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Multiple_occurrences_of_SqlQuery_with_db_parameter_adds_two_parameters(bool async)
    {
        return base.Multiple_occurrences_of_SqlQuery_with_db_parameter_adds_two_parameters(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQuery_queryable_multiple_composed_with_parameters_and_closure_parameters_interpolated(bool async)
    {
        return base.SqlQuery_queryable_multiple_composed_with_parameters_and_closure_parameters_interpolated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_does_not_parameterize_interpolated_string(bool async)
    {
        return base.SqlQueryRaw_does_not_parameterize_interpolated_string(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_in_subquery_with_dbParameter(bool async)
    {
        return base.SqlQueryRaw_in_subquery_with_dbParameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_in_subquery_with_positional_dbParameter_with_name(bool async)
    {
        return base.SqlQueryRaw_in_subquery_with_positional_dbParameter_with_name(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_in_subquery_with_positional_dbParameter_without_name(bool async)
    {
        return base.SqlQueryRaw_in_subquery_with_positional_dbParameter_without_name(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_composed_compiled_with_DbParameter(bool async)
    {
        return base.SqlQueryRaw_queryable_composed_compiled_with_DbParameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_multiple_composed(bool async)
    {
        return base.SqlQueryRaw_queryable_multiple_composed(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_multiple_composed_with_closure_parameters(bool async)
    {
        return base.SqlQueryRaw_queryable_multiple_composed_with_closure_parameters(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_multiple_composed_with_parameters_and_closure_parameters(bool async)
    {
        return base.SqlQueryRaw_queryable_multiple_composed_with_parameters_and_closure_parameters(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_simple_different_cased_columns_and_not_enough_columns_throws(bool async)
    {
        return base.SqlQueryRaw_queryable_simple_different_cased_columns_and_not_enough_columns_throws(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_simple_projection_composed(bool async)
    {
        return base.SqlQueryRaw_queryable_simple_projection_composed(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_queryable_with_null_parameter(bool async)
    {
        return base.SqlQueryRaw_queryable_with_null_parameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_with_db_parameters_called_multiple_times(bool async)
    {
        return base.SqlQueryRaw_with_db_parameters_called_multiple_times(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_with_dbParameter(bool async)
    {
        return base.SqlQueryRaw_with_dbParameter(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_with_dbParameter_mixed(bool async)
    {
        return base.SqlQueryRaw_with_dbParameter_mixed(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_with_dbParameter_mixed_in_subquery(bool async)
    {
        return base.SqlQueryRaw_with_dbParameter_mixed_in_subquery(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SqlQueryRaw_with_dbParameter_without_name_prefix(bool async)
    {
        return base.SqlQueryRaw_with_dbParameter_without_name_prefix(async);
    }

}
