// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.BulkUpdates;

partial class NorthwindBulkUpdatesCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_Where_predicate_with_GroupBy_aggregate(bool async)
    {
        return base.Delete_Where_predicate_with_GroupBy_aggregate(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_Where_using_navigation(bool async)
    {
        return base.Delete_Where_using_navigation(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_with_cross_apply(bool async)
    {
        return base.Delete_with_cross_apply(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_with_join(bool async)
    {
        return base.Delete_with_join(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_with_LeftJoin(bool async)
    {
        return base.Delete_with_LeftJoin(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_with_LeftJoin_via_flattened_GroupJoin(bool async)
    {
        return base.Delete_with_LeftJoin_via_flattened_GroupJoin(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_with_outer_apply(bool async)
    {
        return base.Delete_with_outer_apply(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_with_RightJoin(bool async)
    {
        return base.Delete_with_RightJoin(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Concat_set_constant(bool async)
    {
        return base.Update_Concat_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Except_set_constant(bool async)
    {
        return base.Update_Except_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_FromSql_set_constant(bool async)
    {
        return base.Update_FromSql_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Intersect_set_constant(bool async)
    {
        return base.Update_Intersect_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Union_set_constant(bool async)
    {
        return base.Update_Union_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Distinct_set_constant(bool async)
    {
        return base.Update_Where_Distinct_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Join_set_property_from_joined_single_result_scalar(bool async)
    {
        return base.Update_Where_Join_set_property_from_joined_single_result_scalar(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Join_set_property_from_joined_single_result_table(bool async)
    {
        return base.Update_Where_Join_set_property_from_joined_single_result_table(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Join_set_property_from_joined_table(bool async)
    {
        return base.Update_Where_Join_set_property_from_joined_table(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_OrderBy_set_constant(bool async)
    {
        return base.Update_Where_OrderBy_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_OrderBy_Skip_set_constant(bool async)
    {
        return base.Update_Where_OrderBy_Skip_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_OrderBy_Skip_Take_set_constant(bool async)
    {
        return base.Update_Where_OrderBy_Skip_Take_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_OrderBy_Skip_Take_Skip_Take_set_constant(bool async)
    {
        return base.Update_Where_OrderBy_Skip_Take_Skip_Take_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_OrderBy_Take_set_constant(bool async)
    {
        return base.Update_Where_OrderBy_Take_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_SelectMany_set_null(bool async)
    {
        return base.Update_Where_SelectMany_set_null(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_SelectMany_subquery_set_null(bool async)
    {
        return base.Update_Where_SelectMany_subquery_set_null(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Skip_set_constant(bool async)
    {
        return base.Update_Where_Skip_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Skip_Take_set_constant(bool async)
    {
        return base.Update_Where_Skip_Take_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_Take_set_constant(bool async)
    {
        return base.Update_Where_Take_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_using_navigation_2_set_constant(bool async)
    {
        return base.Update_Where_using_navigation_2_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_Where_using_navigation_set_null(bool async)
    {
        return base.Update_Where_using_navigation_set_null(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_cross_apply_set_constant(bool async)
    {
        return base.Update_with_cross_apply_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_cross_join_cross_apply_set_constant(bool async)
    {
        return base.Update_with_cross_join_cross_apply_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_cross_join_left_join_set_constant(bool async)
    {
        return base.Update_with_cross_join_left_join_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_cross_join_outer_apply_set_constant(bool async)
    {
        return base.Update_with_cross_join_outer_apply_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_cross_join_set_constant(bool async)
    {
        return base.Update_with_cross_join_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_join_set_constant(bool async)
    {
        return base.Update_with_join_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_LeftJoin(bool async)
    {
        return base.Update_with_LeftJoin(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_LeftJoin_via_flattened_GroupJoin(bool async)
    {
        return base.Update_with_LeftJoin_via_flattened_GroupJoin(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_outer_apply_set_constant(bool async)
    {
        return base.Update_with_outer_apply_set_constant(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_PK_pushdown_and_join_and_multiple_setters(bool async)
    {
        return base.Update_with_PK_pushdown_and_join_and_multiple_setters(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_RightJoin(bool async)
    {
        return base.Update_with_RightJoin(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_two_inner_joins(bool async)
    {
        return base.Update_with_two_inner_joins(async);
    }

}
