// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Update;

partial class ComplexCollectionJsonUpdateCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_element_to_complex_collection_mapped_to_json()
    {
        return base.Add_element_to_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_element_to_nested_complex_collection_mapped_to_json()
    {
        return base.Add_element_to_nested_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Change_complex_collection_mapped_to_json_to_null_and_to_empty()
    {
        return base.Change_complex_collection_mapped_to_json_to_null_and_to_empty();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Clear_complex_collection_mapped_to_json()
    {
        return base.Clear_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Complex_collection_with_empty_nested_collections_mapped_to_json()
    {
        return base.Complex_collection_with_empty_nested_collections_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_element_in_complex_collection_mapped_to_json()
    {
        return base.Modify_element_in_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_multiple_complex_properties_mapped_to_json()
    {
        return base.Modify_multiple_complex_properties_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_nested_complex_property_in_complex_collection_mapped_to_json()
    {
        return base.Modify_nested_complex_property_in_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Move_elements_in_complex_collection_mapped_to_json()
    {
        return base.Move_elements_in_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Remove_element_from_complex_collection_mapped_to_json()
    {
        return base.Remove_element_from_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Replace_complex_collection_element_mapped_to_json()
    {
        return base.Replace_complex_collection_element_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Replace_complex_property_mapped_to_json()
    {
        return base.Replace_complex_property_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Replace_entire_complex_collection_mapped_to_json()
    {
        return base.Replace_entire_complex_collection_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Set_complex_collection_to_null_mapped_to_json()
    {
        return base.Set_complex_collection_to_null_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Set_complex_property_mapped_to_json_to_null()
    {
        return base.Set_complex_property_mapped_to_json_to_null();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Set_null_complex_collection_to_non_empty_mapped_to_json()
    {
        return base.Set_null_complex_collection_to_non_empty_mapped_to_json();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Set_null_complex_property_to_non_null_mapped_to_json()
    {
        return base.Set_null_complex_property_to_non_null_mapped_to_json();
    }

}
