// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Update;

partial class StoreValueGenerationWithoutReturningCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_Add_with_different_entity_types_and_all_generated_values(bool async)
    {
        return base.Add_Add_with_different_entity_types_and_all_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_Add_with_different_entity_types_and_generated_values(bool async)
    {
        return base.Add_Add_with_different_entity_types_and_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_Add_with_different_entity_types_and_no_generated_values(bool async)
    {
        return base.Add_Add_with_different_entity_types_and_no_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_Add_with_same_entity_type_and_all_generated_values(bool async)
    {
        return base.Add_Add_with_same_entity_type_and_all_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_Add_with_same_entity_type_and_generated_values(bool async)
    {
        return base.Add_Add_with_same_entity_type_and_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_Add_with_same_entity_type_and_no_generated_values(bool async)
    {
        return base.Add_Add_with_same_entity_type_and_no_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_with_all_generated_values(bool async)
    {
        return base.Add_with_all_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_with_generated_values(bool async)
    {
        return base.Add_with_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Add_with_no_generated_values(bool async)
    {
        return base.Add_with_no_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete(bool async)
    {
        return base.Delete(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_Add_with_same_entity_types(bool async)
    {
        return base.Delete_Add_with_same_entity_types(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_Delete_with_different_entity_types(bool async)
    {
        return base.Delete_Delete_with_different_entity_types(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Delete_Delete_with_same_entity_type(bool async)
    {
        return base.Delete_Delete_with_same_entity_type(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_Modify_with_different_entity_types_and_generated_values(bool async)
    {
        return base.Modify_Modify_with_different_entity_types_and_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_Modify_with_different_entity_types_and_no_generated_values(bool async)
    {
        return base.Modify_Modify_with_different_entity_types_and_no_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_Modify_with_same_entity_type_and_generated_values(bool async)
    {
        return base.Modify_Modify_with_same_entity_type_and_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_Modify_with_same_entity_type_and_no_generated_values(bool async)
    {
        return base.Modify_Modify_with_same_entity_type_and_no_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_with_generated_values(bool async)
    {
        return base.Modify_with_generated_values(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Modify_with_no_generated_values(bool async)
    {
        return base.Modify_with_no_generated_values(async);
    }

}
