// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Update;

partial class UpdatesCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_add_and_remove_self_refs()
    {
        return base.Can_add_and_remove_self_refs();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_change_type_of__dependent_by_replacing_with_new_dependent(bool async)
    {
        return base.Can_change_type_of__dependent_by_replacing_with_new_dependent(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_change_type_of_pk_to_pk_dependent_by_replacing_with_new_dependent(bool async)
    {
        return base.Can_change_type_of_pk_to_pk_dependent_by_replacing_with_new_dependent(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_remove_partial()
    {
        return base.Can_remove_partial();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Can_use_shared_columns_with_conversion()
    {
        return base.Can_use_shared_columns_with_conversion();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Ignore_before_save_property_is_still_generated(bool async)
    {
        return base.Ignore_before_save_property_is_still_generated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Ignore_before_save_property_is_still_generated_graph(bool async)
    {
        return base.Ignore_before_save_property_is_still_generated_graph(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Save_replaced_principal()
    {
        return base.Save_replaced_principal();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Save_with_shared_foreign_key()
    {
        return base.Save_with_shared_foreign_key();
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task SaveChanges_false_processes_all_tracked_entities_without_calling_AcceptAllChanges(bool async)
    {
        return base.SaveChanges_false_processes_all_tracked_entities_without_calling_AcceptAllChanges(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task SaveChanges_processes_all_tracked_entities(bool async)
    {
        return base.SaveChanges_processes_all_tracked_entities(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SaveChanges_throws_for_entities_only_mapped_to_view()
    {
        return base.SaveChanges_throws_for_entities_only_mapped_to_view();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SaveChanges_works_for_entities_also_mapped_to_view()
    {
        return base.SaveChanges_works_for_entities_also_mapped_to_view();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Swap_computed_unique_index_values()
    {
        return base.Swap_computed_unique_index_values();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Swap_filtered_unique_index_values()
    {
        return base.Swap_filtered_unique_index_values();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_non_indexed_values()
    {
        return base.Update_non_indexed_values();
    }

}
