// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Update;

partial class UpdatesCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Ignore_before_save_property_is_still_generated(bool async)
    {
        return base.Ignore_before_save_property_is_still_generated(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public new global::System.Threading.Tasks.Task Ignore_before_save_property_is_still_generated_graph(bool async)
    {
        return base.Ignore_before_save_property_is_still_generated_graph(async);
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Save_with_shared_foreign_key()
    {
        return base.Save_with_shared_foreign_key();
    }

}
