// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.BulkUpdates.Inheritance;

partial class TPTInheritanceBulkUpdatesCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_base_property_on_derived_type(bool async)
    {
        return base.Update_base_property_on_derived_type(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_base_type(bool async)
    {
        return base.Update_base_type(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_base_type_with_OfType(bool async)
    {
        return base.Update_base_type_with_OfType(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_derived_property_on_derived_type(bool async)
    {
        return base.Update_derived_property_on_derived_type(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_interface_in_EF_Property_in_property_expression(bool async)
    {
        return base.Update_with_interface_in_EF_Property_in_property_expression(async);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Update_with_interface_in_property_expression(bool async)
    {
        return base.Update_with_interface_in_property_expression(async);
    }

}
