// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query.Associations.OwnedNavigations;

partial class OwnedNavigationsProjectionCalciteTest
{

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_nested_collection_on_optional_associate(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.Select_nested_collection_on_optional_associate(queryTrackingBehavior);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_optional_associate(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.Select_optional_associate(queryTrackingBehavior);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_optional_nested_on_optional_associate(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.Select_optional_nested_on_optional_associate(queryTrackingBehavior);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_required_nested_on_optional_associate(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.Select_required_nested_on_optional_associate(queryTrackingBehavior);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_root(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.Select_root(queryTrackingBehavior);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Select_root_duplicated(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.Select_root_duplicated(queryTrackingBehavior);
    }

    [Xunit.ConditionalTheory(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task SelectMany_nested_collection_on_optional_associate(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior queryTrackingBehavior)
    {
        return base.SelectMany_nested_collection_on_optional_associate(queryTrackingBehavior);
    }

}
