// <auto-generated> This file is generated by tools/GenerateSkips from a trx run.
// Remove entries by fixing the underlying behavior and regenerating. </auto-generated>

#pragma warning disable xUnit1003 // a skipped theory reports without enumerating data
#pragma warning disable xUnit1024 // a shadowed non-virtual test hides the base slot from discovery

namespace Apache.Calcite.EntityFrameworkCore.FunctionalTests.Query.Associations.OwnedNavigations;

partial class OwnedNavigationsCollectionCalciteTest
{

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Count()
    {
        return base.Count();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task Distinct()
    {
        return base.Distinct();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task GroupBy()
    {
        return base.GroupBy();
    }

    [Xunit.ConditionalFact(Skip = "Not yet supported by the Calcite provider; regenerate with tools/GenerateSkips after fixing.")]
    public override global::System.Threading.Tasks.Task OrderBy_ElementAt()
    {
        return base.OrderBy_ElementAt();
    }

}
